### ISSUE TITLE
No such file or directory: 'pypi.rst'

### ISSUE THREAD

**Issue by madvas** [anentropic/factoryboy-gaendb#2]
Hi,

When I tried to `pip install factoryboy-gaendb` it throws error:

```
Collecting factoryboy-gaendb
  Using cached factoryboy-gaendb-0.1.3.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-EJQN03/factoryboy-gaendb/setup.py", line 10, in <module>
        long_description=open('pypi.rst').read(),
    IOError: [Errno 2] No such file or directory: 'pypi.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-EJQN03/factoryboy-gaendb/setup.py", line 10, in <module>

        long_description=open('pypi.rst').read(),

    IOError: [Errno 2] No such file or directory: 'pypi.rst'
```

Don't you know why this can be? factoryboy-gaendb seems to be exactly what I am searching for ;) 

Thanks a lot!

**Comment by anentropic** [comment]
oh, I will fix now :)

**Comment by anentropic** [comment]
try 0.1.4 now

**Comment by madvas** [comment]
Successfully installed, thanks a lot! Looking forward to try it out ;)
